/**********************************************************************************************************************
 * \file lwiopts.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef __LWIPOPTS_H__
#define __LWIPOPTS_H__

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NO_SYS                  0                   /* Use LwIP without Operating System (no threads, no semaphores, etc.)  */
#define LWIP_NETIF_HOSTNAME     0                   /* Enable hostname option in DHCP                                       */
#define SYS_LIGHTWEIGHT_PROT    1                   /* Disable inter-task protection                                        */
#define TCP_TMR_INTERVAL        50
#define BOARDNAME               "AURIXLK2TC375TP"   /* Board name, also used as hostname                                    */
#define MEM_ALIGNMENT           4                   /* Set memory alignment to 4 byte (32-bit machine)                      */
#define MEM_SIZE                (16 * 1024)         /* Size of the Heap                                                     */
#define MEMP_NUM_PBUF           100
#define MEMP_NUM_TCP_SEG        TCP_SND_QUEUELEN     //64//(12* TCP_SND_BUF/TCP_MSS)
#define MEMP_NUM_TCP_PCB        5
#define PBUF_POOL_SIZE          5
#define PBUF_POOL_BUFSIZE       TCP_MSS
#define TCP_MSS                 1460
#define TCP_SND_BUF             (5 * 1024)   //(28*TCP_MSS)
#define TCP_SND_QUEUELEN        100           //TCP_SND_QUEUELEN must be at least as much as (2 * TCP_SND_BUF/TCP_MSS)
#define TCP_WND                 2048
#define TCP_TTL                 255
#define MEMP_NUM_NETCONN        16
#define TCPIP_MBOX_SIZE         100
#define DEFAULT_TCP_RECVMBOX_SIZE 8


#define LWIP_TCP                1
#define LWIP_SOCKET             1
#define LWIP_ICMP               1
#define LWIP_NETCONN            1

#define TCPIP_THREAD_STACKSIZE          1000
//#define DEFAULT_UDP_RECVMBOX_SIZE       2000
#define DEFAULT_THREAD_STACKSIZE        512

//KEEPALIVE
#define LWIP_TCP_KEEPALIVE      1
#define TCP_KEEPIDLE_DEFAULT    20000   //3秒内双方无数据则发起保活探测
#define TCP_KEEPINTVL_DEFAULT   1000    //1秒发送一次保活探测
#define TCP_KEEPCNT_DEFAULT     3000    //3次探测无响应则断开

#define ARP_MAXAGE        60      // ARP 条目超时时间（秒），超时后自动删除
#define ARP_QUEUEING      2        // 启用 ARP 队列，缓存待发送的数据包
#define ARP_TABLE_SIZE    20      // ARP 缓存表大小
#define LWIP_DHCP               0                   /* Enable DHCP protocol                                                 */
#define TCP_ACK_DELAY 0
#define ETH_PAD_SIZE            2                   /* Add 2 bytes before the Ethernet header to ensure payload alignment   */
#define LWIP_COMPAT_MUTEX       0



#define   __LWIP_DEBUG__                              /* Enable debugging through UART interface                              */
//#define   ENABLE_UART_PRINTF
#define LWIP_NETIF_EXT_STATUS_CALLBACK    1           /* Enable an extended callback function for netif                       */
//#define LWIP_NETIF_STATUS_CALLBACK      1
//#define LWIP_NETIF_LINK_CALLBACK        1
#ifdef __LWIP_DEBUG__
#define LWIP_DEBUG                                             /* Enable LwIP debugging                                                */
#endif
#ifndef IFX_LWIP_DEBUG
#define IFX_LWIP_DEBUG          LWIP_DBG_OFF         /* IFX LwIP debug level set to OFF                                      */
#endif
#define DHCP_DEBUG              LWIP_DBG_OFF        /* Enable DHCP Debug                                                    */
#define NETIF_DEBUG             LWIP_DBG_OFF         /* Enable NETIF Debug      */
#define TCP_DEBUG               LWIP_DBG_OFF         /* Enable TCP Debug                                               */
#define LWIP_DBG_TYPES_ON       LWIP_DBG_STATE      /* Enable only module state debug messages                              */

#endif /* __LWIPOPTS_H__ */
