/**
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */


#include "fl_cfc.h"
#include "fls_app.h"

static FL_DownloadStateType FldownloadStatus;


const FL_BlockDescriptorType FL_BlkInfo[FL_NUM_LOGICAL_BLOCKS] =
{
        //OEM架构应该是三级架构
        //使用16KB做一个极小boot用来启动MCU,并使用HSM来仲裁bootload和APP镜像正确，通过bootload升级APP
        //这里不考虑信息安全
        //PF SC0-SC39 是HSM区域，这部分作boot，不做虑信息安全
        {0xA0000000U, 0xA009FFFFU,0x9FFFFU,   (uint16)0xFFFFU}, /* 640K, HSM_exclusive, for boot */
        {0xA00A0000U, 0xA029FFFFU,0x1FFFFFU,  (uint16)0xFFFFU}, /* 2M,cpu0 code */
        {0xA02A0000U, 0xA02A3FFFU,0x3FFFU,    (uint16)0xFFFFU}, /* 16K, cpu0 interrupt */
        {0xA02A4000U, 0xA02AFFFFU,0xBFFFU,    (uint16)0xFFFFU}, /* 48K, spare */
        {0xA02B0000U, 0xA02FFFFFU,0x4FFFFU,   (uint16)0xFFFFU}, /* 320K,DTD*/

        //不使用SOTA,不使用第二块flash 的HSM
        {0xA0300000U, 0xA04FFFFFU,0x1FFFFFU,  (uint16)0xFFFFU}, /* 2M, cpu1 cpu2 code */
        {0xA0500000U, 0xA0501FFFU,0x1FFFU,    (uint16)0xFFFFU}, /* 8K, cpu1 interrupt  */
        {0xA0502000U, 0xA0503FFFU,0x1FFFU,    (uint16)0xFFFFU}, /* 8K, cpu2 interrupt */
        {0xA0504000U, 0xA050FFFFU,0xBFFFU,    (uint16)0xFFFFU}, /* 48K,spare */
        {0xA0510000U, 0xA05AFFFFU,0x9FFFFU,   (uint16)0xFFFFU}, /* 640K,calibration */
        {0xA05B0000U, 0xA05FFFFFU,0x4FFFFU,   (uint16)0xFFFFU}, /* 320K,spare */

};





