/**
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#ifndef __FLS_APP_H__
#define __FLS_APP_H__


#include "string.h"
#include "user_config.h"


/* the length of programming attempt counter */
#define PROGRAM_SIZE                         (128u)
#define FL_FINGER_PRINT_LENGTH               (0x09U)
#define FL_MAX_SEGMENTS                      (60)
#define MAX_ONCE_CHECKSUM_SIZE               (100000u)
/*invalid UDS services ID*/
#define INVALID_UDS_SERVICES_ID              (0xFFu)
/*=======[T Y P E   D E F I N I T I O N S]====================================*/


/** flashloader download step */
typedef enum
{
    FL_REQUEST_STEP,             /*flash request step*/
    FL_TRANSFER_STEP,            /*flash transfer data step*/
    FL_EXIT_TRANSFER_STEP,       /*exit transfter data step*/
    FL_CHECKSUM_STEP             /*check sum step*/

}tFlDownloadStepType;

/*Erase flash status control*/
typedef enum
{
    START_ERASE_FLASH,            /*start erase flash*/
    DO_ERASING_FLASH,             /*Do erase flash*/
    END_ERASE_FLASH               /*end erase flash*/
}tEraseFlashStep;



/** Segment list information of the block */
typedef struct
{
    uint32 address;              /* Start global address of the segment in flash */
    uint32 length;               /* Length of the segment */
} FL_SegmentInfoType;

/** Needed in interface to the security module. */
typedef struct
{
    uint8 nrOfSegments;                                   /* number of segment */
    FL_SegmentInfoType segmentInfo[FL_MAX_SEGMENTS];      /* segments information */
} FL_SegmentListType;


/* handle the two segments in one page */
typedef struct
{
    uint32 remainAddr;            /* current process start address */
    uint32 remainLength;          /* current process length */
} FL_RemainDataType;

typedef void (*tWDTriggerFct)(void);

/** initialization: input parameters */
typedef struct
{
     uint8 patchLevel;                   /* flash driver patch level version */
     uint8 minorNumber;                  /* flash driver minor version number */
     uint8 majorNumber;                  /* flash driver major version number */
     uint8 reserved1;                    /* reserved for future use, set to 0x00 for now */
     uint8 errorCode;                    /* retrun value / error code: output parameters */
     uint16 reserved2;                   /* reserved for future use, set to 0x0000 for now */
     uint32 address;                     /* logical target address */
     uint32 length;                      /* lenght information (in bytes) */
    const uint8 *data;                   /* pointer to data buffer */
    tWDTriggerFct wdTriggerFct;          /* pointer to watchdog trigger routine */
} tFlashParam;


void FLASH_APP_Init(void);
void Flash_InitDowloadInfo(void);
void Flash_OperateMainFunction(void);
void Flash_InitDowloadInfo(void);

#endif
