/**********************************************************************************************************************
 * \file App_Led1.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Port/Io/IfxPort_Io.h"
#include "uart.h"
#include "App_Config.h"
#include "FreeRTOS.h"
#include "task.h"
#include "gpio.h"
#include <can.h>
#include "semphr.h"
/*********************************************************************************************************************/
/*-----------------------------------------------------Macros--------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED1_BLINKY_PERIOD_MS (250)                         /* The period (in milliseconds) at which LED1 will blink */
extern IfxPort_Pin_Config          test_Pin1;                     /* MCU ms synchronous tigger      */
extern IfxPort_Pin_Config          test_Pin2;                     /* MCU ms synchronous tigger      */
extern IfxCan_Can_Node                g_mcmcanNode[8];
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Initialization function for LED1 app */
uint32 taskcun;

extern devcanfdRXringbuff RxBuff0;
extern devcanfdRXringbuff RxBuff1;
extern devcanfdRXringbuff RxBuff2;
extern SemaphoreHandle_t can0_xSemaphore ;
extern SemaphoreHandle_t can1_xSemaphore ;
extern SemaphoreHandle_t can2_xSemaphore ;
/* Task which runs the LED1 app */
void task_uart(void *arg)
{

    while (1)
    {
        /* Toggle LED1 state */
        taskcun++;
        print("task1 %d\r\n",taskcun);
       // Ifx_Console_print("uart test %d\r\n",taskcun);
        /* Delay 250ms */
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}


void task_led(void *arg)
{

    while (1)
    {
        /* Toggle LED1 state */
        IfxPort_togglePin(test_Pin1.port, test_Pin1.pinIndex);
        taskcun++;
              print("task2 %d\r\n",taskcun);
        /* Delay 250ms */
        vTaskDelay(pdMS_TO_TICKS(250));
    }
}


void task_uds(void *arg)
{
    while (1)
    {
        vTaskDelay(pdMS_TO_TICKS(1));
    }
}

void task_can0_Rx(void *arg)
{
    while(1)
    {
        vTaskDelay(pdMS_TO_TICKS(1));

    }
}


void task_can1_Rx(void *arg)
{
    while(1)
    {

        vTaskDelay(pdMS_TO_TICKS(1));
    }
}


void task_can2_Rx(void *arg)
{
    while(1)
    {

        vTaskDelay(pdMS_TO_TICKS(1));
    }
}


void can_rx_create(void)
{
    xTaskCreate(task_can0_Rx, "task can0 Rx", configMINIMAL_STACK_SIZE, NULL, 10, NULL);
    xTaskCreate(task_can1_Rx, "task can1 Rx", configMINIMAL_STACK_SIZE, NULL, 11, NULL);
    xTaskCreate(task_can2_Rx, "task can2 Rx", configMINIMAL_STACK_SIZE, NULL, 12, NULL);

}



