/**********************************************************************************************************************
 * \file Flash_Programming.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef FLASH_H_
#define FLASH_H_
#include "Ifx_Types.h"
#include "IfxFlash.h"

typedef struct
{
    /** \brief Function pointers of Erase & program routines which are relocated to different memory (PSPR).
     *  The function pointers are used to execute the relocated routines
     */
    void (*pfnEraseSector)(uint32);
    uint8(*pfnWaitUnbusy)(uint32, IfxFlash_FlashType);
    uint8(*pfnEnterPageMode)(uint32);
    void (*pfnLoadPage2X32)(uint32, uint32, uint32);
    void (*pfnWritePage)(uint32);
    int (*pfnFlashErase)(uint32, uint32, IfxFlash_FlashType);
    int (*pfnFlashProgram)(uint32, IfxFlash_FlashType, const void *, uint32);
} PflashFun_t;

typedef enum
{
    FLASH_TYPE_P_FLASH = 0,
    FLASH_TYPE_D_FLASH,
    FLASH_TYPE_UCB_FLASH
} FlashType_e;
typedef struct
{
    int (*pfnEraseFlash)(uint32);
    int (*pfnWriteFlash)(uint32, const void *, uint32);
    FlashType_e     eFlashType;
    int             startSector;
    int             endSector;
    IfxFlash_flashSector *ptflashSector;
    int             sectorNum;
    int             sectorSize;
} FlashOpera_t;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void Hal_Flash_Init(void);
int Hal_Flash_Erase(uint32 eraseAddr, uint32 length);
uint32 Hal_Flash_Read(uint32 readAddr, void *pBuf, uint32 length);
int Hal_Flash_write(uint32 Addr, const void *pBuf, uint32 length);
#endif /* FLASH_H_ */
