/**********************************************************************************************************************
 * \file STM_Interrupt.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <drv/stm.h>
#include "Comm/Ifx_Console.h"
#include "IfxPort.h"
#include "Stm/Std/IfxStm.h"
#include "ifxCpu_irq.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_STM10        100                              /* Priority for interrupt ISR                       */
#define ISR_PRIORITY_STM11        101                              /* Priority for interrupt ISR                       */
#define ISR_PRIORITY_STM20        102                              /* Priority for interrupt ISR                       */
#define STM0                     &MODULE_STM0
#define STM1                     &MODULE_STM1
#define STM2                     &MODULE_STM2
#define IFX_CFG_STM_TICKS_PER_MS  100000
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
volatile uint32 Coer0stm_baseFlag;
volatile uint32 Coer1stm_baseFlag;
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(isrSTM10, 0, ISR_PRIORITY_STM10);
void isrSTM10(void)
{
   IfxStm_clearCompareFlag(&MODULE_STM1, IfxStm_Comparator_0);
    /* Configure STM to generate an interrupt in 1 ms */
   MODULE_STM1.CMP[IfxStm_Comparator_0].B.CMPVAL +=IFX_CFG_STM_TICKS_PER_MS;
   //IfxStm_increaseCompare(&MODULE_STM1, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);
   //lwip sys_now tick count

   Coer0stm_baseFlag++;
   IfxStm_clearCompareFlag(&MODULE_STM1, IfxStm_Comparator_0);
}

IFX_INTERRUPT(isrSTM11, 0, ISR_PRIORITY_STM11);
void isrSTM11(void)
{
   IfxStm_clearCompareFlag(&MODULE_STM1, IfxStm_Comparator_1);
    /* Configure STM to generate an interrupt in 1 ms */
   IfxStm_increaseCompare(&MODULE_STM1, IfxStm_Comparator_1, 100000);
   Coer1stm_baseFlag++;
}


void initSTM11(void)
{
   IfxStm_CompareConfig stm1CompareConfig;                                         /* STM1 Configuration declaration                */

   IfxStm_initCompareConfig(&stm1CompareConfig);                                   /* Initialize a default configuration for STM   */
   stm1CompareConfig.comparator          =IfxStm_Comparator_1;
   stm1CompareConfig.triggerPriority     = ISR_PRIORITY_STM11;
   stm1CompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir1;         /* Select the request source 0                  */
   stm1CompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS *10;           /* First interrupt shall occur after 10 ms      */
   stm1CompareConfig.typeOfService       = IfxSrc_Tos_cpu0;/* CPU0 serves the interrupts                   */
   IfxStm_initCompare(&MODULE_STM1, &stm1CompareConfig);                           /* Initialize the Compare functionality         */
}

void initSTM10(void)
{
   IfxStm_CompareConfig stm0CompareConfig;                                         /* STM1 Configuration declaration                */

   IfxStm_initCompareConfig(&stm0CompareConfig);                                   /* Initialize a default configuration for STM   */
   stm0CompareConfig.comparator          =IfxStm_Comparator_0;
   stm0CompareConfig.triggerPriority     = ISR_PRIORITY_STM10;                      /* Priority of the interrupt generated by STM   */
   stm0CompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;         /* Select the request source 0                  */
   stm0CompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS *10;           /* First interrupt shall occur after 10 ms      */
   stm0CompareConfig.typeOfService       = IfxSrc_Tos_cpu0;                        /* CPU0 serves the interrupts                   */
   IfxStm_initCompare(&MODULE_STM1, &stm0CompareConfig);                            /* Initialize the Compare functionality         */
}




