/**
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#include <AES.h>
#include <UDS_alg_hal.h>

/*******************************************************************************
 * User Include
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
//const static uint8 gs_aKey[] = {0x00u, 0x01u, 0x02u, 0x03u, 0x04u, 0x05u, 0x06u, 0x07u,
//                      0x08u, 0x09u, 0x0au, 0x0bu, 0x0cu, 0x0du, 0x0eu, 0x0fu};

/*here is not init, because this used for software random*/
static uint32 gs_UDS_SWTimerTickCnt;
static uint32 u32RandVal = 0x12345678U;
/*get timer tick cnt for random seed.*/
uint32 TIMER_HAL_GetTimerTickCnt(void)
{
    /*This two variables not init before used, because it used for generate random*/
    uint32 hardwareTimerTickCnt;
    uint32 timerTickCnt;

#if 0
    /*For S32K1xx get timer counter(LPTIMER), get timer count will trigger the period incorrect.*/
    hardwareTimerTickCnt = LPTMR_DRV_GetCounterValueByCount(INST_LPTMR1);
#endif

    timerTickCnt = ((hardwareTimerTickCnt & 0xFFFFu)) | (timerTickCnt << 16u);


    return timerTickCnt;
}
/**
* @brief Sets the seed for the random numbers generator
* @details Writes the given seed into the random numbers generator
* @param[in] u32Seed9 Seed to be used.
* @note Seed 0 would block the generator therefore if 0 is passed, 1 is used
*       as the seed.
* @note Default seed is 0x12345678.
*/
void fsl_srand (uint32 u32Seed9)
{
     /* Value 0 is forbidden because it would block the LFSR */
     if (0U == u32Seed9)
     {   /* Forbidden value */
         u32Seed9++; /* Correct the value */
     }
     u32RandVal = u32Seed9; /* Set the seed */
}

/**
* @brief Returns pseudo-random number
* @details Function generates pseudo-random number using the LFSR algorithm.
* @return Pseudo-random number in the interval from 0 to 0xFFFFFFFF
*/
uint32 fsl_rand(void)
{
    /* Generate the next value in the sequence */
    u32RandVal = (u32RandVal >> 1U) ^ ((0U - (u32RandVal & 1U)) & 0x80200003U);
    /* Return the value */
    return u32RandVal;
}
/*FUNCTION**********************************************************************
 *
 * Function Name : UDS_ALG_HAL_Init
 * Description   : This function initial this module.
 *
 * Implements : UDS_ALG_hal_Init_Activity
 *END**************************************************************************/
void UDS_ALG_HAL_Init(void)
{
}

/*FUNCTION**********************************************************************
 *
 * Function Name : UDS_ALG_HAL_EncryptData
 * Description   : This function is encrpt data.
 *
 * Implements : UDS_ALG_hal_Init_Activity
 *END**************************************************************************/
 boolean UDS_ALG_HAL_EncryptData(const uint8 *i_pPlainText, const uint32 i_dataLen, uint8 *o_pCipherText)
{
	boolean ret = FALSE;

#ifdef EN_ALG_SW
	aes((sint8 *)i_pPlainText, i_dataLen, (sint8 *)&gs_aKey[0], (sint8 *)o_pCipherText);
#endif

	


	return ret;
}

/*FUNCTION**********************************************************************
 *
 * Function Name : UDS_ALG_HAL_DecryptData
 * Description   : This function is decrypt data.
 *
 * Implements : UDS_ALG_hal_Init_Activity
 *END**************************************************************************/
 boolean UDS_ALG_HAL_DecryptData(const uint8 *i_pCipherText, const uint32 i_dataLen, uint8 *o_pPlainText)
{
	boolean ret = FALSE;

#ifdef EN_ALG_SW
	deAes((sint8 *)i_pCipherText, i_dataLen, (sint8 *)&gs_aKey[0], (sint8 *)o_pPlainText);	
#endif

	return ret;
}

/*FUNCTION**********************************************************************
 *
 * Function Name : UDS_ALG_HAL_GetRandom
 * Description   : This function is get random.
 *
 * Implements : UDS_ALG_hal_Init_Activity
 *END**************************************************************************/
boolean UDS_ALG_HAL_GetRandom(const uint32 i_needRandomDataLen, uint8 *o_pRandomDataBuf)
{
	boolean ret = TRUE;
	uint8 index = 0u;
	uint8 *pRandomTmp = NULL_PTR;
	uint32 random = (uint32)&index;

	if((0u == i_needRandomDataLen) || (NULL_PTR == o_pRandomDataBuf))
	{
		ret = FALSE;
	}
#if 1
	random = TIMER_HAL_GetTimerTickCnt();
	
	random |= (gs_UDS_SWTimerTickCnt << 16u);
	fsl_srand(random);

	if(TRUE == ret)
	{		
		pRandomTmp = (uint8 *)&random;
		
		for(index = 0u; index < i_needRandomDataLen; index++)
		{
			if(((index & 0x03u) == 0x03u))
			{
				/*get random*/
				random = fsl_rand();
			}
			
			o_pRandomDataBuf[index] = pRandomTmp[index & 0x03];
		}
	}
#else
	random = 0u;
	for(index = 0; index < i_needRandomDataLen; index++)
	{
		o_pRandomDataBuf[index] = random;

		random += 0x11u;
	}

#endif


	return ret;

}

/*UDS software timer tick*/
void UDS_ALG_HAL_AddSWTimerTickCnt(void)
{
#ifdef EN_ALG_SW
	gs_UDS_SWTimerTickCnt++;
#endif
}

/*FUNCTION**********************************************************************
 *
 * Function Name : UDS_ALG_HAL_Deinit
 * Description   : This function initial this module.
 *
 * Implements : UDS_ALG_Deinit_Activity
 *END**************************************************************************/
void UDS_ALG_HAL_Deinit(void)
{


}

/******************************************************************************
 * EOF
 *****************************************************************************/
