/**
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or
 * organization obtaining a copy of the software and accompanying
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */
#ifndef __UDS__CFG_H__
#define __UDS__CFG_H__

/*********************Include headers************************/
#include "user_config.h"
#include "fls_app.h"
#include "dflash.h"
/**********************************************************/
#define BOOTLOADER_TYPE (0x0Fu)
#define BOOTLOADER_SW_VERSION {BOOTLOADER_TYPE, 0x02, 0x0, 0x00}
#define BOOTLOADER_HW_VERSION {BOOTLOADER_TYPE, 0x02, 0x0, 0x00}
#define MAX_FLASH_DATA_LEN (200u)



typedef struct
{
    uint32 xUdsId;
    uint32 xDataLen;
    uint8 aDataBuf[150u];
    /*tx message call back*/
    void (*pfUDSTxMsgServiceCallBack)(uint8);
} tUdsAppMsgInfo;


void  UDS_DoResetMCU(uint8 Txstatus);
void  Flash_SavedReceivedCheckSumCrc(uint32 i_receivedCrc);
void  UDS_DoEraseFlash(uint8 TxStatus);
void  UDS_DoCheckSum(uint8 TxStatus);
uint8 UDS_IsEraseMemoryRoutineControl(const tUdsAppMsgInfo *m_pstPDUMsg);
uint8 UDS_IsCheckSumRoutineControl(const tUdsAppMsgInfo *m_pstPDUMsg);
uint8 UDS_IsCheckProgrammingDependency(const tUdsAppMsgInfo *m_pstPDUMsg);
void  RequetMoreTimeSuccessfulFromHost(uint8 i_txMsgStatus);
uint8 UDS_DoCheckProgrammingDependency(void);
uint8 UDS_IsReceivedKeyRight(const uint8 *i_pReceivedKey,const uint8 *i_pTxSeed, const uint8 KeyLen);
uint8 UDS_IsGetVersion(const tUdsAppMsgInfo *m_pstPDUMsg);
#endif
