/********************************************************************************************************************
 * \file MULTICAN_FD.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MCMCAN_FD_H_
#define MCMCAN_FD_H_ 1

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ifx_Types.h"
#include "IfxCan_Can.h"
#include "IfxCan.h"
#include "IfxPort.h"
#include "stm.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define FLEXCAN_DATA_FIELD_LEN      (8u)
#define FLEXCAN_FD_DATA_FIELD_LEN   (64u)
#define MAXIMUM_CAN_FD_DATA_PAYLOAD 64                         /* Define maximum CAN payload in bytes               */
#define MODULE_CAN0_RAM    0xF0200000u
#define MODULE_CAN1_RAM    0xF0210000u
#define NODE0_RAM_OFFSET   0x0
#define NODE1_RAM_OFFSET   0x1000
#define NODE2_RAM_OFFSET   0x2000
#define NODE3_RAM_OFFSET   0x3000

#define ISR_PRIORITY_CAN00_RX         10                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN01_RX         11                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN02_RX         12                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN03_RX         13                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN10_RX         14                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN11_RX         15                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN12_RX         16                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN13_RX         17                           /* Define the CAN RX interrupt priority              */

#define ISR_PRIORITY_CAN00_TX         30                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN01_TX         31                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN02_TX         32                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN03_TX         33                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN10_TX         34                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN11_TX         35                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN12_TX         36                           /* Define the CAN TX interrupt priority              */
#define ISR_PRIORITY_CAN13_TX         37                           /* Define the CAN TX interrupt priority              */

#define ISR_PRIORITY_CAN00_ERR         60                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN01_ERR         61                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN02_ERR         62                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN03_ERR         63                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN10_ERR         64                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN11_ERR         65                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN12_ERR         66                           /* Define the CAN RX interrupt priority              */
#define ISR_PRIORITY_CAN13_ERR         67                           /* Define the CAN RX interrupt priority              */
/*********************************************************************************************************************/
/*--------------------------------------------------Data Structures--------------------------------------------------*/
/*********************************************************************************************************************/

typedef struct
{
    uint8  baudrate;
    uint8  FDbaudrate;
    uint8  samplingpoint;
    uint8  FDsamplingpoint;
    uint8  listenMode; //0  only receive 1 only transmit 2 receive and transmit
    uint8  errframeEnable;
    uint16 spare1;
    uint8  status[4];  /* status[0]: DBC, status[1]: SLEEP, status[2]: app_up */
    uint8  spare3[32];
} canInitConfigType;

typedef struct
{
    uint8  baudrate;
    uint8  FDbaudrate;
    uint8  samplingpoint;
    uint8  FDsamplingpoint;
    uint8  listenMode; //0  only receive 1 only transmit 2 receive and transmit
    uint16 spare0;

    uint16 syncJumpWidth;
    uint16 FDsyncJumpWidth;

} canChangeConfigType;
typedef enum
{
    CanCommunicationStatus_Success = 0,
    CanCommunicationStatus_Error_notExpectedMessageId,
    CanCommunicationStatus_Error_notExpectedLengthCode,
    CanCommunicationStatus_Error_notExpectedFrameMode,
    CanCommunicationStatus_Error_notExpectedData
} canCommunicationStatusType;


typedef struct
{
    IfxCan_Can_Pins pin;// 引脚
    uint32 ramBaseAddr;// MCMCAN起始地址
    uint16 ramBaseAddrOffset;//message 偏移地址
    IfxCan_NodeId nodeId;// 节点号
    Ifx_Priority priorityTX;//发送的优先级
    Ifx_Priority priorityRX;//接收的优先级
    Ifx_Priority priorityERR;//接收的优先级
    IfxCan_InterruptLine interruptLineTX;//发送的中断号
    IfxCan_InterruptLine interruptLineRX;//接收的中断号
    IfxCan_InterruptLine interruptLineERR;//接收的中断号
}NodeCanCfg_t;

typedef struct
{
    uint8 presdiv;
    uint8 rjw;
    uint8 pseg1;
    uint8 pseg2;
    uint8 propseg;
}BaudFDInfo;

typedef enum
{
  BPS_NULL=0,
  BPS_50K,
  BPS_100K,
  BPS_125K,
  BPS_250K,
  BPS_500K,
  BPS_1MK,
  BPS_NUM,
}bps_goal;

typedef enum
{
  BPS_notuse=0,
  BPS_1m,
  BPS_2m,
  BPS_4m,
  BPS_5m,
  BPS_8m,
  BPS_FD_NUM,
}bpsfd_goal;

typedef enum
{
  samplePoint_700=0,
  samplePoint_750,
  samplePoint_800,
  samplePoint_850,
  samplePoint_875,
  samplePoint_900,
  samplePoint_NUM,

}samplingpoint;

typedef enum
{
  fdsamplePoint_700=0,
  fdsamplePoint_750,
  fdsamplePoint_800,
  fdsamplePoint_850,
  fdsamplePoint_875,
  fdsamplePoint_NUM,


}FDsamplingpoint;

typedef struct
{
   uint32  messageid;
   uint32  ms;
   uint16  us;
   uint8   dlc;
   uint8   BSR;
   uint8   errFlag;
   uint8   channel;
   uint8   frameMode;
   uint8   ESI;
   uint8   IfxCan_MessageIdLength;
   uint8   remoteTransmitRequest;
   uint8   spare1;
   uint8   spare2;
} devcanRXringbuffmessage;

typedef struct
{
  uint32  messageid;
  uint32  ms;
  uint16  us;
  uint8   dlc;
  uint8   BSR;
  uint8   errFlag;
  uint8   channel;
  uint8   frameMode;
  uint8   ESI;
  uint8   IfxCan_MessageIdLength;
  uint8   remoteTransmitRequest;
  uint8   spare1;
  uint8   spare2;
  uint8 rxData[MAXIMUM_CAN_FD_DATA_PAYLOAD];          /* Received CAN data array     */
} devcanfdRXringbuff;

typedef struct
{
   devcanRXringbuffmessage msg;

   union{
      uint8 rxData[8];          /* Received CAN data array     */
      struct{
         uint32 word0;
         uint32 word1;
            };
        };
} devcanRXringbuff;

typedef struct
{
    canInitConfigType canInitConfig[8];  //波特率
    uint8 flag;
    uint8 sumCheck[4];//app程序校验和
    uint8 len[4];     //app程序长度
    uint8 appVer[4];  //版本信息和升级页数。
    uint8 pageNum[4];
    uint8 status[4];  /* status[0]: DBC, status[1]: SLEEP, status[2]: app_up */
}stParam_t;
/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void initMcmcan(uint8 nodeid,canInitConfigType *canInitConfig);
uint8 transmitCanMessage(uint8 nodeid,uint32 messageID,uint32 *data,IfxCan_DataLengthCode len,IfxCan_MessageIdLength extended,IfxCan_FrameMode mode);
void  Can_Node_enableInterrupt(uint8 nodeid, IfxCan_Interrupt interrupt);
void  Can_Node_disenableInterrupt(uint8 nodeid ,IfxCan_Interrupt interrupt);
void canModeChaerge(uint8 nodeid,uint8  mode);
void canBaudrateChaerge(uint8 nodeid,canChangeConfigType  *Config);
void usr_can_BaudrateChange(IfxCan_Can_Node *node,canChangeConfigType *canChangeConfig);
void usr_Can_readMessage(IfxCan_Can_Node *node, uint8 readFromRxFifo, devcanfdRXringbuff *buff);
#endif /* MCMCAN_FD_H_ */
