/********************************************************************************************************************
 * \file MCMCAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2020
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <gpio.h>
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxPort_Pin_Config          can_stb1;                       /* Global STB configuration and control structure      */
IfxPort_Pin_Config          can_stb2;
IfxPort_Pin_Config          can_en;                        /* Global STB configuration and control structure      */
IfxPort_Pin_Config          can_power;                        /* Global STB configuration and control structure      */
IfxPort_Pin_Config          net_power_en;                  /* switch RTL8367 power en      */
//IfxPort_Pin_Config          test_Pin1;                     /* MCU ms synchronous tigger      */
IfxPort_Pin_Config          test_Pin2;                     /* MCU ms synchronous tigger      */
//IfxPort_Pin_Config        spi_cs;                      /* Global  SPI CS configuration and control structure      */

IfxPort_Pin                 alert;                         /* Global ip_select_key2 configuration and control structure      */
IfxPort_Pin                 ctr_power;                     /* Global ip_select_key2 configuration and control structure      */
/* Function to initialize the all gpio */
void initGPIO(void)
{
    /* ======================================================================
     * Configuration of the pins connected to the all gpios:
     * ======================================================================
     *  - define the GPIO port
     *  - define the GPIO pin that is connected to the LED
     *  - define the general GPIO pin usage (no alternate function used)
     *  - define the pad driver strength
     * ======================================================================
     */

    //output pin
    can_stb1.port      = &MODULE_P20;
    can_stb1.pinIndex  = 1;
    can_stb1.mode      = IfxPort_OutputIdx_general;
    can_stb1.padDriver = IfxPort_PadDriver_ttlSpeed1;
    can_stb2.port      = &MODULE_P20;
    can_stb2.pinIndex  = 0;
    can_stb2.mode      = IfxPort_OutputIdx_general;
    can_stb2.padDriver = IfxPort_PadDriver_ttlSpeed1;

    can_en.port      = &MODULE_P33;
    can_en.pinIndex  = 0;
    can_en.mode      = IfxPort_OutputIdx_general;
    can_en.padDriver = IfxPort_PadDriver_ttlSpeed1;

    net_power_en.port      = &MODULE_P33;
    net_power_en.pinIndex  = 2;
    net_power_en.mode      = IfxPort_OutputIdx_general;
    net_power_en.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

   // test_Pin1.port      = &MODULE_P02;
   // test_Pin1.pinIndex  = 3;
  //  test_Pin1.mode      = IfxPort_OutputIdx_general;
  //  test_Pin1.padDriver = IfxPort_PadDriver_ttl3v3Speed1;
    test_Pin2.port      = &MODULE_P02;
    test_Pin2.pinIndex  = 4;
    test_Pin2.mode      = IfxPort_OutputIdx_general;
    test_Pin2.padDriver = IfxPort_PadDriver_ttl3v3Speed1;

    //input pin
    alert.port = &MODULE_P10;
    alert.pinIndex = 1;

    ctr_power.port = &MODULE_P33;
    ctr_power.pinIndex = 1;

    /* Initialize the input mode  , which keep the pin at pull down  as default state */

    IfxPort_setPinModeInput(ctr_power.port, ctr_power.pinIndex,  IfxPort_Mode_inputPullDown);
    IfxPort_setPinModeInput(alert.port, alert.pinIndex,  IfxPort_Mode_inputPullDown);

    //output pin
    /* Initialize the pins connected to level "low" */
    IfxPort_setPinHigh(can_stb1.port, can_stb1.pinIndex); //STB1
    IfxPort_setPinHigh(can_stb2.port, can_stb2.pinIndex); //STB2
    IfxPort_setPinHigh(can_en.port, can_en.pinIndex);  //CAN_EN
   // IfxPort_setPinLow(test_Pin1.port, test_Pin1.pinIndex);
    IfxPort_setPinLow(test_Pin2.port, test_Pin2.pinIndex);
    IfxPort_setPinLow(net_power_en.port, net_power_en.pinIndex);

    /* Set the pin input/output mode for both pins connected to the LEDs */
    IfxPort_setPinModeOutput(can_stb1.port, can_stb1.pinIndex, IfxPort_OutputMode_pushPull, can_stb1.mode);
    IfxPort_setPinModeOutput(can_stb2.port, can_stb2.pinIndex, IfxPort_OutputMode_pushPull, can_stb2.mode);
    IfxPort_setPinModeOutput(can_en.port, can_en.pinIndex, IfxPort_OutputMode_pushPull, can_en.mode);
    IfxPort_setPinModeOutput(net_power_en.port, net_power_en.pinIndex, IfxPort_OutputMode_pushPull, net_power_en.mode);
   // IfxPort_setPinModeOutput(test_Pin1.port, test_Pin1.pinIndex, IfxPort_OutputMode_pushPull, test_Pin1.mode);
    IfxPort_setPinModeOutput(test_Pin2.port, test_Pin2.pinIndex, IfxPort_OutputMode_pushPull, test_Pin2.mode);
    /* Set the pad driver mode for both pins connected to the LEDs */
    IfxPort_setPinPadDriver(can_stb1.port, can_stb1.pinIndex, can_stb1.padDriver);
    IfxPort_setPinPadDriver(can_stb2.port, can_stb2.pinIndex, can_stb2.padDriver);
    IfxPort_setPinPadDriver(can_en.port, can_en.pinIndex, can_en.padDriver);
    IfxPort_setPinPadDriver(net_power_en.port, net_power_en.pinIndex, net_power_en.padDriver);

   // IfxPort_setPinPadDriver(test_Pin1.port, test_Pin1.pinIndex, test_Pin1.padDriver);
    IfxPort_setPinPadDriver(test_Pin2.port, test_Pin2.pinIndex, test_Pin2.padDriver);

}
